# Generated by Django 4.1.3 on 2022-12-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_zonas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_cumple', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Zonas',
        ),
    ]
