# Generated by Django 4.1.3 on 2022-12-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_fechas_delete_zonas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechas',
            name='fecha_cumple',
            field=models.DateField(blank=True, null=True),
        ),
    ]
