# Generated by Django 4.1.3 on 2022-12-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_fechas_fecha_cumple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechas',
            name='fecha_cumple',
            field=models.DateField(blank=True, null=True, verbose_name='fecha_cumple(mm/dd/yyyy)'),
        ),
    ]
