# Generated by Django 4.1.3 on 2022-12-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_lista_delete_fechas_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='precio',
        ),
    ]
