# Generated by Django 4.1.3 on 2022-12-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_lista_cantidad_remove_lista_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lista',
            new_name='Lista_Compras',
        ),
    ]
