# Generated by Django 4.1.3 on 2022-12-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_compras_delete_lista_compras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='nombre',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='edad',
            new_name='valor',
        ),
    ]
