# Generated by Django 4.1.3 on 2022-12-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_rename_nombre_compras_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='valor',
            field=models.FloatField(),
        ),
    ]
