# Generated by Django 4.1.3 on 2022-12-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
